# Generated by Django 4.0.5 on 2022-07-07 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_cat',
            field=models.CharField(max_length=100, null=True, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_cat',
            field=models.SlugField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seed.category', verbose_name='Категорії'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публікація'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_prod',
            field=models.CharField(max_length=100, null=True, verbose_name='Насіння'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час останьї зміни'),
        ),
    ]
