# Generated by Django 4.0.5 on 2022-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0002_alter_category_name_cat_alter_category_slug_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Опис'),
        ),
    ]
