# Generated by Django 4.0.5 on 2022-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_alter_product_image_1_alter_product_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Види насіння', 'verbose_name_plural': 'Види насіння'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупець', 'verbose_name_plural': 'Покупець'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['date_added'], 'verbose_name': 'Деталі замовлення', 'verbose_name_plural': 'Деталі замовлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['time_create'], 'verbose_name': 'Насіння', 'verbose_name_plural': 'Насіння'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
