# Generated by Django 4.0.5 on 2022-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0006_alter_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_sale',
            field=models.BooleanField(default=False, null=True, verbose_name='Топ продаж'),
        ),
    ]
