# Generated by Django 4.0.5 on 2022-07-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0008_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
