# Generated by Django 4.0.5 on 2022-08-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0012_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='comment',
            field=models.TextField(max_length=1000, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.customer', verbose_name='Покупець'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mail',
            field=models.CharField(max_length=100, null=True, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mail_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер відділення'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pay',
            field=models.CharField(max_length=100, null=True, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=100, null=True, verbose_name='Поштовий індекс'),
        ),
    ]
