# Generated by Django 4.0.5 on 2022-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0013_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seeder_landing_rate',
            field=models.IntegerField(null=True, verbose_name='Норма висадки(сівалка)'),
        ),
    ]
